server:
  port: 8888

  # 驱动配置信息
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://@mysql_ip@:@mysql_port@/musjoy?useUnicode=true&characterEncoding=utf8&useSSL=true&serverTimezone=UTC
    username : @mysql_username@
    password : @mysql_password@
    driverClassName : com.mysql.jdbc.Driver

  mvc:
    view:
      suffix: .html
      prefix: /pages/
  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456


mybatis:
  mapper-locations: classpath*:mapper/*.xml


APP_KEY: e7c2f1bcd45e6876c65a2878Master
MASTER_SECRET: 6c0f8255bf4860306254ec9f


# 分布式文件系统fastdfs配置
fdfs:
  # socket连接超时时长
  soTimeout: 1500
  # 连接tracker服务器超时时长
  connectTimeout: 600
  pool:
    # 从池中借出的对象的最大数目
    max-total: 153
    # 获取连接时的最大等待毫秒数100
    max-wait-millis: 102
  # 缩略图生成参数，可选
  thumbImage:
    width: 150
    height: 150
  # 跟踪服务器tracker_server请求地址,支持多个，这里只有一个，如果有多个在下方加- x.x.x.x:port
  trackerList:
    - 47.95.234.254:8310
  #
  # 存储服务器storage_server访问地址
  web-server-url: http://47.95.234.255:8410/

